### ISSUE TITLE
After Deducting money its showing failed

### ISSUE THREAD

**Issue by sagar-roy109** [aifaiz/ipay88-woocommerce#9]
Everything is working fine. But after deducting money its showing order payment status failed.
Can you help me please ?

**Comment by aifaiz** [comment]
Hi,

sorry for the late reply. could you provide more information on that? like, `error logs` or something related? I cant be much help since its a `vague` question

**Comment by beeing** [comment]
This is because the combined string for hashing on response is wrong. I've fixed it as below:

```php
$combined = $this->merchantCode.$mcode.$payid.$refno.$amnt_final.$cur.$status;
```

**Comment by MalBouq** [comment]
Hello
I am getting the same issue. Ipay88 says all is going well and transaction is successful (amount is debited from the account)
But on my woocommerce website, it's notified as failed and instead of getting a "thank you page", the client sees this message:
"Unfortunately your order cannot be processed as the originating bank/merchant has declined your transaction. Please attempt your purchase again."

iPay88 technical support says they send a successful transaction message to my website and the issue may come from AiCS plugin.
Any help please?
Thank you

**Comment by aifaiz** [comment]
hi everyone. thank you for your participation in this plugin. I had updated a small tweak on the code.
it probably like @beeing mention. but when i go to the official tech spec documentation. it has to be the `merchantKey` first, then `merchant ID` and so on.


anyhow, i had done some tweak and see how it will go. reply in this issue if its not yet resolved.

Thanks
AiFAiZ
